Remove web forms
rpiambulance/website pull request #183
Opened 2024-09-14 04:44 UTC by CKegel

Remove web forms on standby, CPR, and Contact Us pages. This is a band aid patch until we get a new website up and running.
![Screenshot from 2024-09-14 00-37-07](https://github.com/user-attachments/assets/017bbc9b-ea07-4bcc-961b-02c06c6caefe)
![Screenshot from 2024-09-14 00-37-03](https://github.com/user-attachments/assets/30a4f786-16fc-4127-91a2-f2eb3b79548a)
![Screenshot from 2024-09-14 00-02-14](https://github.com/user-attachments/assets/7d19c1a7-93b1-48a9-a273-99baf2167438)

2024-09-14 14:37 UTC, ddbruce requested changes

2024-09-14 14:37 UTC, ddbruce commented on views/contact.html
> +        <p class="lead">Expierencing a medical emergency? <span style="color: #c52d2f;"><strong>Dial 911</strong></span></p>
typo

2024-09-14 14:37 UTC, ddbruce commented on views/contact.html
> +        <p class="lead">Shoot us an email at <a href="mailto:officers@rpiambulance.com">officers@rpiambulance.com</a> - Or come visit us!</p>
please change to:

`&mdash;or come visit us!`

2024-09-14 14:37 UTC, ddbruce commented on views/coverage-details.html
Why was this deleted?

2024-09-14 14:37 UTC, ddbruce commented on views/coverage.html
> +        <h3 class="text-center"><br><strong>Please note: A minimum of 2 weeks notice is required for event standbys.</strong></h3>
Please change to "two"

2024-09-14 14:42 UTC, CKegel commented on views/coverage-details.html
This is a "ghost/dead page" if you will. Note is doesn't reflect the current website and is not referenced anywhere else in the code.

2024-09-14 14:51 UTC, ddbruce commented on views/coverage-details.html
👍

2024-10-21 15:52 UTC, ddbruce approved these changes
Lgtm

2024-10-22 16:09 UTC, merged